### ISSUE TITLE
Create a Graphical User Interface (GUI) for the Inventory System

### ISSUE THREAD

**Issue by locallhosts** [locallhosts/inventory#1]
Description: Create a simple GUI to allow users to interact with the inventory system more easily. The GUI can have buttons for adding, updating, and deleting products, as well as displaying the inventory.

**Comment by locallhosts** [comment]
Create a simple GUI to allow users to interact with the inventory system more easily. 
The GUI can have buttons for adding, updating, and deleting products,
 as well as displaying the inventory.

**Comment by locallhosts** [comment]
Create a new branch with a meaningful name like gui-improvement.
Add the necessary code to create a GUI using a Python library like tkinter, 
PyQt, or wxPython.
Create buttons for adding, updating, and deleting products, as well as displaying the inventory.
Test the GUI to make sure it's functioning as expected.

**Comment by locallhosts** [comment]
fixed

**Comment by kenmatlala** [comment]
what number are you using now +27721646797 is my number
